"""
Defines file management helpers used across the library

Uses `platformdirs` to define platform-specific directories in which all
runtime data produced by the library is persisted. In addition, uses
`importlib` to define a helper to resolve the location of built-in data
shipped with the library when installed via pip
"""

from importlib import resources
from pathlib import Path

from platformdirs import PlatformDirs

HOST_STORAGE = PlatformDirs(
    appname="mirumoji",
    appauthor=False,
    ensure_exists=False,
)
r"""
Filesystem locations used by the server and launcher

All user-writable paths derive from `platformdirs` and are keyed by the app's
name only. Keeping them unversioned means data, config, and logs survive a
version upgrade instead of being orphaned under a per-version subfolder

info: One Folder On Windows, Several On macOS / Linux
    - On Windows every path lives under a single `%LOCALAPPDATA%\mirumoji\`
      folder, with cache and logs as `Cache\` / `Logs\` subfolders of it

    - On macOS and Linux the data, config, cache, and state roots are
      separate top-level directories, each holding its own `mirumoji` folder,
      so no single folder holds everything. The `mirumoji reset` cleanup
      accounts for this (see `launcher/core/storage.py`)

tip: Storage Paths
    === "Windows"
        ```text
        user_data_path   = %LOCALAPPDATA%\mirumoji\
        user_config_path = %LOCALAPPDATA%\mirumoji\
        user_cache_path  = %LOCALAPPDATA%\mirumoji\Cache\
        user_state_path  = %LOCALAPPDATA%\mirumoji\
        user_log_path    = %LOCALAPPDATA%\mirumoji\Logs\
        ```

    === "MacOS"
        ```text
        user_data_path   = ~/Library/Application Support/mirumoji/
        user_config_path = ~/Library/Application Support/mirumoji/
        user_cache_path  = ~/Library/Caches/mirumoji/
        user_state_path  = ~/Library/Application Support/mirumoji/
        user_log_path    = ~/Library/Logs/mirumoji/
        ```

    === "Linux / Unix"
        ```text
        # WARNING
        # platformdirs honours the $XDG_*_HOME variables for these
        # The following are the defaults when they are not set

        user_data_path   = ~/.local/share/mirumoji/
        user_config_path = ~/.config/mirumoji/
        user_cache_path  = ~/.cache/mirumoji/
        user_state_path  = ~/.local/state/mirumoji/
        user_log_path    = ~/.local/state/mirumoji/log/
        ```

info: Directory Creation
    This object is created with `ensure_exists=False`, so none of the
    `HOST_*` directories exist merely because the library was imported
"""

# --- Server ---

HOST_MEDIA_PATH: Path = HOST_STORAGE.user_data_path / "media_files"
"""
The server's media root (`user_data_path / media_files`)

Directory in which the server stores all media that was generated or uploaded
by users at runtime. Contains sub-directories for every mirumoji `profile`
under which the media was uploaded or generated
"""


HOST_DB_PATH: Path = HOST_STORAGE.user_data_path / "mirumoji.db"
"""
The server's `SQLite Database` file (`user_data_path / mirumoji.db`)

The full path in which the `mirumoji` database will be created or initialised
at server startup. The database holds all mirumoji `profile` information, along
with file references relative to `HOST_MEDIA_PATH`
"""

# --- Shared ---

HOST_LOG_PATH: Path = HOST_STORAGE.user_log_path
"""
The library's log directory (`user_log_path`)

Directory in which all `*.log` files generated by the library will be
persisted. This path is used by both the server and the launcher.

info: Application Logs
    - `Mirumoji Server` logs are saved here as `backend.log`

    - `Mirumoji Launcher` logs are saved here as `launcher.log`
"""

# --- Launcher ---

HOST_REPO_PATH: Path = HOST_STORAGE.user_data_path / "source"
"""
Directory in which the launcher stores a checked out clone of the `mirumoji`
repo to use for local Docker Image builds (`user_data_path / source`)
"""

HOST_RENDER_DIR: Path = HOST_STORAGE.user_cache_path / "compose"
"""
Directory in which the launcher stores the rendered Docker Compose files
generated from the template before running `docker compose -f`
"""

HOST_CONFIG_FILE: Path = HOST_STORAGE.user_config_path / "mirumoji.env"
"""
File in which the launcher persists user configuration data as environment
variables for the server to consume
"""

# --- Packaged Resources (Shipped In The Wheel) ---


def _package_path(*parts: str) -> Path:
    """
    Resolves a path inside the installed `mirumoji` package

    Uses `importlib.resources` to correctly look up the path regardless of how
    the package was installed

    Args:
        *parts (str): Path segments relative to the package root

    Returns:
        The concrete filesystem path to the resource
    """
    root = resources.files("mirumoji")
    return Path(str(root.joinpath(*parts)))


DOCKER_DIR: Path = _package_path("docker")
"""
The installation-specific path to the `mirumoji/docker` package-data directory
"""


COMPOSE_TEMPLATE_PATH: Path = DOCKER_DIR / "compose" / "compose.yaml"
"""
The installation-specific path to the `mirumoji/docker/compose/compose.yaml`
package-data Docker Compose template
"""
