"""
This module defines constant and environemnt variables that are used
throughout the application for consistency.

Attributes:
  LOGGING_LEVEL (str): Environment variable defining the level of the python
      logger. Defaults to "INFO"
  SRT_DEFAULT_SYS_MSG (str): Environment variable defining the LLM's
      default system message when told to fix the subtitles generated by
      Whisper
  BREAKDOWN_DEFAULT_SYS_MSG (str): Environment variable defining the LLM's
      default system message when explaining the nuance of word(s) in a
      Japanese sentence
  MODAL_GPU (str): Environment variable defining which GPU to use inside the
      Modal container. Defaults to `A10G`
  MODAL_IMAGE (str): Environment variable defining the Docker Repository URL
      of the pre-built image to use inside the Modal container. Defaults to
      `docker.io/svdc1/mirumoji-modal-gpu:latest`
"""

import os
from pathlib import Path

from platformdirs import PlatformDirs

from .. import __version__

HOST_DATA_DIRS = PlatformDirs(
    appname="mirumoji",
    appauthor=False,
    version=__version__,
    ensure_exists=True,
)

HOST_MEDIA_PATH: Path = HOST_DATA_DIRS.user_data_path / "media_files"

HOST_LOG_PATH: Path = HOST_DATA_DIRS.user_log_dir

_SRT_DEFAULT = (
    "You are an expert subtitle editor for Japanese anime.\n"
    "You understand:\n"
    "  - Conversational Japanese, character names, "
    "honorifics onomatopoeia and scene-specific slang.\n"
    "  - How to pick the correct Kanji/Kana from phonetic "
    "transcriptions based on context.\n"
    "  - Natural sentence flow and typical timing for "
    "subtitles.\n"
    "Your job is to **clean only the text** of each SRT cue:\n"
    "  - Fix mis-recognized Kanji or Kana.\n"
    "  - Merge cues that split a single sentence "
    "(new cue's start = earlier, end = later).\n"
    "  - Remove any pure gibberish or repeated song-lyric "
    "artifacts.\n  - "
    "Insert correct punctuation (。？！、) and adjust spacing.\n\n"  # noqa: RUF001
    "**You must not**:\n  - Change any start/end timestamps.\n  - Renumber "
    "beyond simple sequential order.\n  - Add or remove cues "
    "(only merge as above).\n  - Add any commentary or explanations.\n\n"
    "Output **only** the cleaned `.srt` file content."
)

SRT_DEFAULT_SYS_MSG: str = os.getenv(
    "MIRUMOJI_SRT_DEFAULT_SYS_MSG",
    _SRT_DEFAULT,
)

_BREAKDOWN_DEFAULT = (
    "You are a Japanese language API that explains the specific nuance "
    "of specified word(s) in a Japanese sentence.\n"
    "Respond concisely in no more than 100 words.\n"
    "Specified word(s) MUST be in Japanese\n"
    "All other explanation text MUST be in English\n"
    "In your response:\n"
    "  DO NOT OUTPUT the language name or the word 'nuance';\n"
    "  DO NOT OUTPUT the context sentence ;\n"
    "  DO NOT OUTPUT romaji/furigana or any notes on pronunciation;\n"
    "  Conclude with the specific nuance within the context sentence."
)

BREAKDOWN_DEFAULT_SYS_MSG: str = os.getenv(
    "MIRUMOJI_BREAKDOWN_DEFAULT_SYS_MSG",
    _BREAKDOWN_DEFAULT,
)

MODAL_GPU: str = os.getenv("MIRUMOJI_MODAL_GPU", "A10G")

MODAL_IMAGE: str = os.getenv(
    "MIRUMOJI_MODAL_IMAGE",
    "docker.io/svdc1/mirumoji-modal-gpu:latest",
)

LOGGING_LEVEL: str = os.getenv("MIRUMOJI_LOGGING_LEVEL", "INFO").upper()
