"""
This module defines constant and environemnt variables that are used
throughout the application for consistency.

Attributes:
  LOG_DIR (Path): Environment variable defining the path to the directory in
      which application logs will be stroed. Defaults to
      `Path.home() / '.mirumoji_logs'`
  LOGGING_LEVEL (str): Environment variable defining the level of the python
      logger. Defaults to "INFO"
  BASE_MEDIA_DIR (Path): Environment variable defining the path to the main
      directory in which to store user media. Defaults to `Path('media_files')`
  TEMP_DIR (Path): Directory to use for temporary operations inside
      `BASE_MEDIA_DIR` resolved as `BASE_MEDIA_DIR / 'temp'`.
  FWHISPER_GPT_DEFAULT_SYS_MSG (str): Environment variable defining the LLM's
      default system message when told to fix the subtitles generated by
      Whisper.
  MODAL_GPU (str): Environment variable defining which GPU to use inside the
      Modal container. Defaults to `A10G`
  MODAL_IMAGE (str): Environment variable defining the Docker Repository URL
      of the pre-built image to use inside the Modal container. Defaults to
      `docker.io/svdc1/mirumoji-modal-gpu:latest`
"""

import os
from pathlib import Path

LOG_DIR: Path = Path(
    os.getenv("MIRUMOJI_LOG_DIR", Path.home() / ".mirumoji_logs")
)

BASE_MEDIA_DIR: Path = Path(
    os.getenv("MIRUMOJI_BASE_MEDIA_DIR", "media_files")
)

TEMP_DIR: Path = BASE_MEDIA_DIR / "temp"

_WHISPER_GPT_DEFAULT = (
    "You are an expert subtitle editor for Japanese anime.\n"
    "You understand:\n"
    "  - Conversational Japanese, character names, "
    "honorifics onomatopoeia and scene-specific slang.\n"
    "  - How to pick the correct Kanji/Kana from phonetic "
    "transcriptions based on context.\n"
    "  - Natural sentence flow and typical timing for "
    "subtitles.\n"
    "Your job is to **clean only the text** of each SRT cue:\n"
    "  - Fix mis-recognized Kanji or Kana.\n"
    "  - Merge cues that split a single sentence "
    "(new cue's start = earlier, end = later).\n"
    "  - Remove any pure gibberish or repeated song-lyric "
    "artifacts.\n  - "
    "Insert correct punctuation (。？！、) and adjust spacing.\n\n"  # noqa: RUF001
    "**You must not**:\n  - Change any start/end timestamps.\n  - Renumber "
    "beyond simple sequential order.\n  - Add or remove cues "
    "(only merge as above).\n  - Add any commentary or explanations.\n\n"
    "Output **only** the cleaned `.srt` file content."
)

FWHISPER_GPT_DEFAULT_SYS_MSG: str = os.getenv(
    "MIRUMOJI_FWHISPER_GPT_DEFAULT_SYS_MSG",
    _WHISPER_GPT_DEFAULT,
)

MODAL_GPU: str = os.getenv("MIRUMOJI_MODAL_GPU", "A10G")

MODAL_IMAGE: str = os.getenv(
    "MIRUMOJI_MODAL_IMAGE",
    "docker.io/svdc1/mirumoji-modal-gpu:latest",
)

LOGGING_LEVEL: str = os.getenv("MIRUMOJI_LOGGING_LEVEL", "INFO").upper()
