blank_issues_enabled: true
contact_links:
    - name: Contact
      about: Feel free to send me an email at svdc1mail@gmail.com
    - name: Discussions
      url: https://github.com/svdC1/mirumoji/discussions
      about: Please ask and answer questions here.
