blank_issues_enabled: true
contact_links:
    - name: Email the Maintainer
      url: mailto:svdc1mail@gmail.com
      about: For private questions or security reports.
    - name: Discussions
      url: https://github.com/svdC1/mirumoji/discussions
      about: Ask and answer questions, share setups and ideas.
