services:
    frontend:
        image: mirumoji_frontend_local:latest
        ports:
            - "80:80" # HTTP Nginx
            - "443:443" #HTTPS Nginx
        environment:
            - HOST_LAN_IP=${HOST_LAN_IP}
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        image: mirumoji_backend_cpu_local:latest
        ports:
            - "8000:8000"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - MODAL_TOKEN_ID=${MODAL_TOKEN_ID}
            - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET}
        volumes:
            - data:/app/data/
            - media_files:/app/media_files
        networks:
            - app-network

volumes:
    data:
    media_files:

networks:
    app-network:
        driver: bridge
