name: Frontend licenses bundle

on:
    workflow_dispatch:

jobs:
    licenses:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Generate NOTICE + legal texts
              run: |
                  mkdir apps/frontend/frontend-licenses
                  npm install -g license-checker-rseidelsohn
                  cd apps/frontend && \
                  npm install --omit=dev
                  cd apps/frontend && \ 
                  npm install yui-lint
                  cd apps/frontend && \
                  npx license-checker-rseidelsohn --production \
                    --markdown \
                    --out apps/frontend/frontend-licenses/NOTICE-frontend.md \
                    --files apps/frontend/frontend-licenses
                  curl -L \
                    "https://raw.githubusercontent.com/nodejs/node/v22.x/LICENSE" \
                    -o apps/frontend/frontend-licenses/NodeJS_LICENSE.txt
                  curl -L \
                    "https://raw.githubusercontent.com/nginx/nginx/master/LICENSE" \
                    -o apps/frontend/frontend-licenses/NGINX_LICENSE.txt

            - name: Upload licenses folder
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-licenses
                  path: apps/frontend/frontend-licenses
