name: Build and Push Frontend Docker Image

# Controls when the workflow will run
on:
    release:
        types: [published] # Trigger only when a release is published via the UI

    # Run manually
    workflow_dispatch:

jobs:
    build-and-push-frontend:
        runs-on: ubuntu-latest

        # Grant GITHUB_TOKEN permissions to write packages
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # Set up Docker Buildx for multi-platform builds
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            # Login to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            # Login to the container registry (GitHub Container Registry)
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Extract metadata (tags, labels) for Docker
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  # Define the image name structure. Uses ghcr.io/<owner>/<repo>
                  images: |
                      ghcr.io/${{ github.repository_owner }}/mirumoji
                      docker.io/${{ secrets.DOCKER_USERNAME }}/mirumoji
                  tags: |
                      # immutable
                      type=semver,pattern={{version}},prefix=frontend-
                      # rolling-tag
                      type=raw,value=frontend-latest

            - name: Clean up disk space before build
              run: |
                  docker system prune -af || true
                  sudo rm -rf /usr/share/dotnet || true
                  sudo rm -rf /usr/local/lib/android || true
                  sudo rm -rf /opt/ghc || true
                  sudo rm -rf /tmp/* || true
                  sudo apt-get clean

            # Build and push the Docker image
            - name: Build and push Frontend Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/frontend # Build context is the root of the frontend
                  file: ./apps/frontend/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
